# Generated by Django 3.2 on 2021-04-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210419_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Banned', 'Заблокирован'), ('Unbanned', 'Разблокирован')], max_length=30, verbose_name='Статус'),
        ),
    ]
